### ISSUE TITLE
If not enough items, also request Wikidata items without an image

### ISSUE THREAD

**Issue by nicolas-raoul** [ragesoss/diderot#1]
Wikidata has tons of items missing an image, and an API to query that.

It could be a good complement in places where https://github.com/Abbe98/articles-by-lat-lon-without-images-service returns nothing.

Query example:
https://query.wikidata.org/#SELECT%20%3Fitem%20%28SAMPLE%28%3Fitem_label%29%20as%20%3Flabel%29%20%28SAMPLE%28%3Flocation%29%20as%20%3Flocation%29%20WHERE%20%7B%0A%20%20%0A%20%20%23%20Around%20a%20given%20location%0A%20%20SERVICE%20wikibase%3Aaround%20%7B%20%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP625%20%3Flocation%20.%20%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%28138.6%2035.6%29%22%5E%5Egeo%3AwktLiteral.%20%23%20TODO%20Replace%20with%20the%20longitude%2Flatitude%20you%20want%20here.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aradius%20%225%22%20.%20%0A%20%20%7D%0A%20%20%0A%20%20%23%20Without%20an%20image%0A%20%20MINUS%20%7B%3Fitem%20wdt%3AP18%20%5B%5D%20.%20%7D%0A%20%20%0A%20%20%23%20Get%20the%20label%20in%20English%2C%20or%20any%20other%20language%20if%20no%20English%20label%20available.%0A%20%20OPTIONAL%20%7B%3Fitem%20rdfs%3Alabel%20%3Fitem_label.%7D%0A%7D%0AGROUP%20BY%20%3Fitem

**Comment by Abbe98** [comment]
Actually a lot of people have asked for Wikidata support so I might add it to Abbe98/articles-by-lat-lon-without-images-service. 

I would probably just add support for `wikidata` as a valid value for the `wiki` parameter.

**Comment by nicolas-raoul** [comment]
That would be an elegant solution indeed!

PS: I love the name of this app!

**Comment by Abbe98** [comment]
Tracked on my end in: Abbe98/articles-by-lat-lon-without-images-service#5

**Comment by ragesoss** [comment]
Cool. It looks like the range you can use for a Wikidata query is a lot wider too. (I got timely results with radius 100.)

**Comment by nicolas-raoul** [comment]
Radius 100 kilometers is quite brutal I think :-)
As a watch client app, I guess you only want to show the nearest points, right? In that case it might make sense to:
- Call Wikidata with a 1 kilometer radius,
- If not enough results, call with a 3 kilometers radius,
- If not enough results, call with a 20 kilometers radius,
- etc

And use a fake GPS (or test-specific code) to test your app in a place with many missing images such as Soho (NYC).
Cheers!

**Comment by Abbe98** [comment]
So now this is live in my API:
http://tools.wmflabs.org/articles-by-lat-lon-without-images/index.php?wiki=wikidata&lat=58.1&lon=16.1&radius=1500

It returns the exactly same format as when fetching articles and radius is still specified in meters.

**Comment by nicolas-raoul** [comment]
Wonderful!
articles-by-lat-lon-without-images-service seems to works fine and very fast for Wikidata.

Do you have any idea how real-time it is? I fixed the label of an item, and it does not seem to be reflected after a few minutes. Maybe Wikidata has a cache or something?
While not important for now, in the future it would be cool if you could upload the picture you have taken for that item, and see it disappear from the map immediately (WikiShootMe! does this).

Thanks a lot!

**Comment by Abbe98** [comment]
@nicolas-raoul it should only take a few minutes. Try using your SparQL query above and see if you gets the same result.

**Comment by ragesoss** [comment]
Excellent. I'll try to integrate this tomorrow. I think the suggested approach of only making a Wikidata query if nothing comes up from Wikipedia makes sense.

I think the Wikipedia geo api has a hard limit on the radius, which seems to be about 5km. So I'll use the same one for this, even though Wikidata doesn't have the same restriction.

**Comment by Abbe98** [comment]
@ragesoss querying Wikidata with more than a 5km radius is likely to result in a timeout in dense areas too.

**Comment by ragesoss** [comment]
@Abbe98 true, but if there are no Wikipedia results, then it's unlikely to be a dense area, right? I'm working on that assumption, and keeping the 10k radius for both Wikipedia and Wikidata, for now.

If it becomes a problem, I guess the solution would be to start small and get larger. But a fixed radius seems to be working fine with good performance at this point.

I'll try to get customization of color done too, and then push a release.

**Comment by Abbe98** [comment]
@ragesoss if there is no Wikipedia articles without images it could still be a dense area. 

If it ends up being a problem let me know and I could add a `limit` parameter.
