### ISSUE TITLE
Can't find it in the Pebble app

### ISSUE THREAD

**Issue by waldyrious** [ragesoss/diderot#4]
I'm new to the Pebble ecosystem -- maybe it is not compatible with my version (Pebble 2), and is hidden because of that? Or does it take a while to become available in the app store? (And if the latter is true, is there a way to install it?)

**Comment by ragesoss** [comment]
It should be compatible. It's a watchface, rather than an app, so you need to search for it in the watchfaces.

**Comment by waldyrious** [comment]
Oh yeah, that speaks to my inexperience :) I found it, thanks!
